FROM openjdk:8
EXPOSE 8080
COPY C:/Users/pjeeri/.jenkins/workspace/pavani/CICD-github-actions/target/CICD-github-actions.jar CICD-github-actions.jar
ENTRYPOINT ["java","-jar","CICD-github-actions.jar"]
